# .goreleaser.yml
before:
  hooks:
    - go mod tidy

builds:
  - env: ["CGO_ENABLED=0"]
    binary: pover
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arch64

kos:
  - repository: ghcr.io/sparkymat/pover
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

docker_signs:
  - artifacts: manifests
