// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"uk-flex uk-flex-column uk-background-default uk-height-viewport uk-padding-small\" style=\"gap: 15px;\"><div class=\"uk-flex\"><button class=\"uk-button uk-button-default\" hx-on:click=\"editor.setValue(&#39;&#39;)\" hx-confirm=\"Are you sure you want to clear?\">Clear</button><div class=\"uk-flex-1\"></div><button class=\"uk-button uk-button-primary\" hx-post=\"/generate_image\" hx-vals=\"js:{code: editor.getValue()}\" hx-target=\"#image\">Render</button></div><div class=\"uk-flex-1 uk-flex\" style=\"gap: 15px;\"><div class=\"uk-flex-1 uk-flex uk-flex-column\"><div><h3>Code</h3></div><div class=\"uk-flex-1 uk-background-secondary\" id=\"editor\"></div></div><div class=\"uk-flex-1 uk-flex uk-flex-column\"><div><h3>Output</h3></div><div class=\"uk-flex-1 uk-background-muted\" id=\"image\"></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
